genes:
  - INS
  - GCG
  - ADM
  - SST
  - CA2
  - HMHB1
  - KRTAP22-1
  - KRTAP22-2
  - KRTAP20-3
  - TMSB10
  - TMSB15A
num_foldings: 2
colabfold_exec: "/mnt/c/Users/lahat/colabfold/localcolabfold/colabfold-conda/bin/colabfold_batch"
